import type { ClientConfig } from "@/core/types";

export const abcGymConfig: ClientConfig = {
  slug: "abcgym",
  templateSlug: "gym",
  businessName: "ABC Gym",
  tagline: "Push Beyond Your Limits",
  logo: {
    url: "/logos/abc-gym.svg",
    alt: "ABC Gym Logo",
  },
  colors: {
    primary: "#e65100",
    secondary: "#bf360c",
    accent: "#ff9100",
    background: "#0a0a0a",
    surface: "#141414",
    text: "#fafafa",
    textMuted: "#a0a0a0",
    border: "#262626",
  },
  hero: {
    title: "Push Beyond Your Limits",
    subtitle: "ABC Gym — Where Champions Are Made",
    description: "Join the most advanced fitness facility in the city. State-of-the-art equipment, world-class trainers, and a community that drives results.",
    ctaText: "Start Free Trial",
    ctaLink: "#contact",
    secondaryCtaText: "View Programs",
    secondaryCtaLink: "#services",
    backgroundImage: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1920&q=80",
  },
  about: {
    title: "More Than Just a Gym",
    subtitle: "Your Transformation Partner",
    description: "At ABC Gym, we believe fitness is a journey, not a destination. Our 20,000 sq ft facility is equipped with the latest machines, free weights, and dedicated spaces for every workout style. Our certified trainers are committed to helping you achieve your goals, whether you're a beginner or a competitive athlete.",
    image: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
    stats: [
      { label: "Active Members", value: "2,500+" },
      { label: "Expert Trainers", value: "15" },
      { label: "Years of Experience", value: "12" },
      { label: "Programs Offered", value: "30+" },
    ],
  },
  services: {
    title: "Our Training Programs",
    subtitle: "Find the perfect program for your fitness goals",
    services: [
      {
        title: "Strength Training",
        description: "Build muscle and increase strength with our comprehensive strength programs led by certified trainers.",
        icon: "🏋️",
        price: "$49/mo",
      },
      {
        title: "HIIT Classes",
        description: "High-intensity interval training sessions that torch calories and boost cardiovascular fitness.",
        icon: "⚡",
        price: "$39/mo",
      },
      {
        title: "Yoga & Flexibility",
        description: "Improve flexibility, balance, and mental clarity with our diverse yoga class offerings.",
        icon: "🧘",
        price: "$35/mo",
      },
      {
        title: "Personal Training",
        description: "One-on-one coaching tailored to your specific goals with dedicated progress tracking.",
        icon: "🎯",
        price: "$89/session",
      },
      {
        title: "CrossFit",
        description: "Functional fitness workouts that challenge your entire body through varied high-intensity movements.",
        icon: "💪",
        price: "$59/mo",
      },
      {
        title: "Boxing & MMA",
        description: "Learn self-defense while getting an incredible full-body workout with expert martial arts instructors.",
        icon: "🥊",
        price: "$55/mo",
      },
    ],
  },
  gallery: {
    title: "Our Facility",
    subtitle: "Take a virtual tour of ABC Gym",
    images: [
      { src: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80", alt: "Main gym floor", caption: "Spacious Main Floor" },
      { src: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=600&q=80", alt: "Weight training area", caption: "Free Weights Zone" },
      { src: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=80", alt: "Cardio section", caption: "Cardio Section" },
      { src: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600&q=80", alt: "Group fitness studio", caption: "Group Class Studio" },
      { src: "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=600&q=80", alt: "Boxing ring", caption: "Boxing Ring" },
      { src: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=600&q=80", alt: "Yoga studio", caption: "Yoga & Wellness" },
    ],
  },
  testimonials: {
    title: "What Our Members Say",
    subtitle: "Real stories from real members",
    testimonials: [
      {
        name: "Sarah Mitchell",
        role: "Member",
        company: "2 Years",
        content: "ABC Gym completely transformed my life. The trainers are incredible, the equipment is top-notch, and the community keeps me motivated every single day.",
        rating: 5,
      },
      {
        name: "David Chen",
        role: "Athlete",
        company: "3 Years",
        content: "As a competitive athlete, I need a gym that matches my intensity. ABC Gym delivers with their CrossFit program and expert coaching staff.",
        rating: 5,
      },
      {
        name: "Emily Rodriguez",
        role: "Member",
        company: "1 Year",
        content: "I was intimidated by gyms before joining ABC. The welcoming atmosphere and patient trainers made all the difference. Down 30 lbs and feeling amazing!",
        rating: 5,
      },
    ],
  },
  faq: {
    title: "Frequently Asked Questions",
    subtitle: "Everything you need to know about ABC Gym",
    faqs: [
      { question: "What are your operating hours?", answer: "We're open Monday to Friday from 5 AM to 11 PM, Saturday 6 AM to 10 PM, and Sunday 7 AM to 8 PM." },
      { question: "Do you offer a free trial?", answer: "Yes! We offer a complimentary 7-day trial for all new members. No commitment required." },
      { question: "Is personal training included?", answer: "All memberships include one complimentary personal training session. Additional sessions can be purchased separately." },
      { question: "Do you have locker rooms and showers?", answer: "Yes, we have full locker rooms with showers, saunas, and complimentary toiletries." },
    ],
  },
  contact: {
    title: "Get in Touch",
    subtitle: "Ready to start your fitness journey?",
    address: "123 Fitness Avenue, Downtown, NY 10001",
    phone: "+1 (555) 123-4567",
    email: "hello@abcgym.com",
    hours: "Mon-Fri: 5AM-11PM | Sat: 6AM-10PM | Sun: 7AM-8PM",
    socials: [
      { platform: "Instagram", url: "https://instagram.com/abcgym" },
      { platform: "Facebook", url: "https://facebook.com/abcgym" },
      { platform: "Twitter", url: "https://twitter.com/abcgym" },
    ],
  },
  cta: {
    title: "Ready to Transform Your Body?",
    description: "Join ABC Gym today and get your first month free. No contracts, no hidden fees — just results.",
    buttonText: "Claim Free Trial",
    buttonLink: "#contact",
    secondaryButtonText: "View Pricing",
    secondaryButtonLink: "#services",
  },
  footer: {
    links: [
      { label: "About", href: "#about" },
      { label: "Programs", href: "#services" },
      { label: "Gallery", href: "#gallery" },
      { label: "Contact", href: "#contact" },
    ],
    socials: [
      { platform: "Instagram", url: "https://instagram.com/abcgym" },
      { platform: "Facebook", url: "https://facebook.com/abcgym" },
      { platform: "Twitter", url: "https://twitter.com/abcgym" },
    ],
  },
};
