import type { ClientConfig } from "@/core/types";

export const shreeDentalConfig: ClientConfig = {
  slug: "shreedental",
  sectionOrder: ["hero", "about", "services", "testimonials", "gallery", "cta", "contact", "faq", "footer"],
  sectionLabels: { services: "Treatments" },
  businessName: "Shree Dental Clinic",
  tagline: "Your Smile, Our Priority",
  logo: {
    url: "/logos/shree-dental.svg",
    alt: "Shree Dental Clinic Logo",
  },
  colors: {
    primary: "#0284c7",
    secondary: "#0369a1",
    accent: "#38bdf8",
    background: "#ffffff",
    surface: "#f0f9ff",
    text: "#0f172a",
    textMuted: "#64748b",
    border: "#e2e8f0",
  },
  hero: {
    title: "Experience World-Class Dental Care",
    subtitle: "Shree Dental Clinic",
    description: "Providing comprehensive dental treatments with advanced technology in a comfortable and hygienic environment.",
    ctaText: "Book Appointment",
    ctaLink: "#contact",
    secondaryCtaText: "Our Treatments",
    secondaryCtaLink: "#services",
    backgroundImage: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1920&q=80",
  },
  about: {
    title: "About Shree Dental Clinic",
    subtitle: "Excellence in Dentistry",
    description: "At Shree Dental Clinic, we are dedicated to providing personalized dental care. Our experienced team uses state-of-the-art technology to ensure you receive the best possible treatment for a healthy, beautiful smile.",
    image: "https://images.unsplash.com/photo-1598256989800-fea5ce5146f2?w=800&q=80",
    stats: [
      { label: "Happy Patients", value: "5,000+" },
      { label: "Expert Doctors", value: "5" },
      { label: "Years Experience", value: "15" },
      { label: "Treatments Available", value: "20+" },
    ],
  },
  services: {
    title: "Our Treatments",
    subtitle: "Comprehensive dental care for your whole family",
    services: [
      {
        title: "General Dentistry",
        description: "Routine check-ups, cleanings, and preventative care to maintain your oral health.",
        icon: "🦷",
        price: "Consultation from $50",
      },
      {
        title: "Cosmetic Dentistry",
        description: "Enhance your smile with teeth whitening, veneers, and smile makeovers.",
        icon: "✨",
        price: "Prices vary",
      },
      {
        title: "Orthodontics",
        description: "Straighten your teeth with traditional braces or clear aligners.",
        icon: "😁",
        price: "From $2000",
      },
      {
        title: "Dental Implants",
        description: "Permanent solutions for missing teeth that look and feel natural.",
        icon: "🔩",
        price: "From $1000",
      },
      {
        title: "Root Canal Treatment",
        description: "Save infected teeth with our painless root canal procedures.",
        icon: "🩺",
        price: "From $300",
      },
      {
        title: "Pediatric Dentistry",
        description: "Gentle and friendly dental care specialized for children.",
        icon: "👶",
        price: "Consultation from $40",
      },
    ],
  },
  gallery: {
    title: "Our Clinic",
    subtitle: "State-of-the-art facilities for your comfort",
    images: [
      { src: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=600&q=80", alt: "Reception", caption: "Welcoming Reception" },
      { src: "https://images.unsplash.com/photo-1598256989800-fea5ce5146f2?w=600&q=80", alt: "Treatment Room", caption: "Modern Treatment Room" },
      { src: "https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=600&q=80", alt: "Dental Equipment", caption: "Advanced Equipment" },
      { src: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&q=80", alt: "Waiting Area", caption: "Comfortable Waiting Area" },
    ],
  },
  testimonials: {
    title: "Patient Reviews",
    subtitle: "What our patients say about us",
    testimonials: [
      {
        name: "Rahul Sharma",
        role: "Patient",
        company: "Google Review",
        content: "Excellent clinic with very professional doctors. The treatment was completely painless. Highly recommended!",
        rating: 5,
      },
      {
        name: "Priya Patel",
        role: "Patient",
        company: "Google Review",
        content: "Very clean and hygienic environment. The staff is polite and the doctors explain everything clearly.",
        rating: 5,
      },
      {
        name: "Amit Kumar",
        role: "Patient",
        company: "Google Review",
        content: "Got my root canal done here. Best dental experience I've had. Thank you Shree Dental Clinic!",
        rating: 5,
      },
    ],
  },
  faq: {
    title: "Frequently Asked Questions",
    subtitle: "Common questions about our dental services",
    faqs: [
      { question: "Do I need an appointment?", answer: "While we accept walk-ins, we highly recommend booking an appointment to avoid waiting." },
      { question: "Is the treatment painful?", answer: "We use the latest techniques and local anesthesia to ensure your treatment is as comfortable and pain-free as possible." },
      { question: "How often should I visit the dentist?", answer: "We recommend visiting the dentist for a check-up and cleaning every 6 months." },
      { question: "Do you accept insurance?", answer: "Yes, we accept most major dental insurance plans. Please contact our reception for details." },
    ],
  },
  contact: {
    title: "Contact Us",
    subtitle: "Book your appointment today",
    address: "123 Health Avenue, Medical District",
    phone: "+91 98765 43210",
    email: "info@shreedentalclinic.com",
    hours: "Mon-Sat: 10AM-8PM | Sun: Closed",
    socials: [
      { platform: "Instagram", url: "https://instagram.com/shreedental" },
      { platform: "Facebook", url: "https://facebook.com/shreedental" },
    ],
  },
  cta: {
    title: "Ready for a Healthier Smile?",
    description: "Book a consultation with our experts today and take the first step towards perfect oral health.",
    buttonText: "Book Now",
    buttonLink: "#contact",
    secondaryButtonText: "Call Us",
    secondaryButtonLink: "tel:+919876543210",
  },
  footer: {
    links: [
      { label: "About", href: "#about" },
      { label: "Treatments", href: "#services" },
      { label: "Contact", href: "#contact" },
    ],
    socials: [
      { platform: "Instagram", url: "https://instagram.com/shreedental" },
      { platform: "Facebook", url: "https://facebook.com/shreedental" },
    ],
  },
};
